#!/usr/bin/env bash
set -euo pipefail

# This file is normally generated by the Hypr-Lab installer.
for fm in nautilus thunar dolphin nemo pcmanfm-qt pcmanfm; do
    if command -v "$fm" >/dev/null 2>&1; then
        exec "$fm"
    fi
done

echo "Hypr-Lab: no supported file manager detected." >&2
exit 1
