monitor=,preferred,auto,1

$terminal = kitty

exec-once = waybar -c ~/.config/waybar-lab/config.jsonc -s ~/.config/waybar-lab/style.css

#DECLARATIONS
$mainKey = SUPER

#app_keybinds
bind = $mainKey, C, exec, $terminal						# open_terminal
bind = $mainKey, M, exit  							# quit_hyprland
bind = $mainKey, B, exec, ~/.config/hypr-lab/settings/browser.sh		# Open the browser in declarated to the sh file.
bind = $mainKey, E, exec, ~/.config/hypr-lab/settings/filemanager.sh		# Open the file manager in declarated to the sh file.

#Workspaces_switch
bind = $mainKey, 1, workspace, 1
bind = $mainKey, 2, workspace, 2 
bind = $mainKey, 3, workspace, 3
bind = $mainKey, 4, workspace, 4
bind = $mainKey, 5, workspace, 5

#Move active window other workspace
bind = $mainKey SHIFT, 1, movetoworkspace, 1
bind = $mainKey SHIFT, 2, movetoworkspace, 2
bind = $mainKey SHIFT, 3, movetoworkspace, 3
bind = $mainKey SHIFT, 4, movetoworkspace, 4
bind = $mainKey SHIFT, 5, movetoworkspace, 5

#app_launcher
bind = $mainKey, SPACE, exec, rofi -show drun					#Open app launcher

#window
bind = $mainKey, Q, killactive							# Kill active window

input {
    kb_layout = hu
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

decoration {
    rounding = 10
}

animations {
    enabled = yes
}
