monitor=,preferred,auto,1

$terminal = kitty

exec-once = waybar -c ~/.config/waybar-lab/config.jsonc -s ~/.config/waybar-lab/style.css

#DECLARATIONS
$mainKey = SUPER

#app_keybinds
bind = $mainKey, C, exec, $terminal						# open_terminal
bind = $mainKey, M, exit  							# quit_hyprland
bind = $mainKey, B, exec, ~/.config/hypr-lab/settings/browser.sh		# Open the browser in declarated to the sh file.
bind = $mainKey, E, exec, ~/.config/hypr-lab/settings/filemanager.sh		# Open the file manager in declarated to the sh file.


#app_launcher
bind = $mainKey, SPACE, exec, rofi -show drun					#Open app launcher

#window
bind = $mainKey, Q, killactive							# Kill active window

input {
    kb_layout = hu
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

decoration {
    rounding = 10
}

animations {
    enabled = yes
}
