monitor=,preferred,auto,1

$terminal = kitty

exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = awww-daemon
exec-once = ~/.config/hypr/hyprlab-scripts/toggle-border-anim.sh

#======================
#KEYBINDS IN Hypr-Lab
#======================

$mainKey = SUPER

#app_keybinds
bind = $mainKey, C, exec, $terminal						# open_terminal
bind = $mainKey, M, exit  							# quit_hyprland
bind = $mainKey, B, exec, ~/.config/hypr/settings/browser.sh			# Open the browser in declarated to the sh file.
bind = $mainKey, E, exec, ~/.config/hypr/settings/filemanager.sh		# Open the file manager in declarated to the sh file.

#Wallpaper_change
bind = $mainKey, W, exec, ~/.config/hypr/hyprlab-scripts/change-wallpaper-lab.sh

#Power_Management
bind = $mainKey, P, exec, ~/.config/rofi/powermenu.sh				#Show the power menu

#Screenshots
bind = $mainKey SHIFT, S, exec, ~/.config/hypr/hyprlab-scripts/screenshot-area.sh
bind = $mainKey SHIFT, A, exec, ~/.config/hypr/hyprlab-scripts/screenshot-full.sh

#Workspaces_switch
bind = $mainKey, 1, workspace, 1
bind = $mainKey, 2, workspace, 2 
bind = $mainKey, 3, workspace, 3
bind = $mainKey, 4, workspace, 4
bind = $mainKey, 5, workspace, 5

#Move active window other workspace
bind = $mainKey SHIFT, 1, movetoworkspace, 1
bind = $mainKey SHIFT, 2, movetoworkspace, 2
bind = $mainKey SHIFT, 3, movetoworkspace, 3
bind = $mainKey SHIFT, 4, movetoworkspace, 4
bind = $mainKey SHIFT, 5, movetoworkspace, 5

#Resize_active_window
bind = $mainKey CTRL, right, resizeactive, 100 0
bind = $mainKey CTRL, left, resizeactive, -100 0
bind = $mainKey CTRL, down, resizeactive, 0 100
bind = $mainKey CTRL, up, resizeactive, 0 -100

#Window_floating_mode
bind = $mainKey, T, togglefloating,
bind = $mainKey, F, fullscreen, 0

#Floating_window_move_resize
bindm = $mainKey, mouse:272, movewindow	
bindm = $mainKey, mouse:273, resizewindow

#app_launcher
bind = $mainKey, SPACE, exec, rofi -show drun -theme ~/.config/rofi/launcher.rasi					#Open app launcher

# Ablak border animáció ki/be kapcsolása
bind = SUPER ALT, A, exec, ~/.config/hypr/hyprlab-scripts/toggle-border-anim.sh

#window
bind = $mainKey, Q, killactive							# Kill active window

input {
    kb_layout = hu
}

#======================
#Hypr-Lab rice section
#======================

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(b026ffcc)
    col.inactive_border = rgba(22222255)
}

decoration {
    rounding = 5
    active_opacity = 0.80 					#active_window_opacity
    inactive_opacity = 0.70					#inactive_window_opacity
    fullscreen_opacity = 1.0					#fullscreen_opacity

    blur {
    	enabled = true						#true or false
	size = 1
	passes = 5
	new_optimizations = true
	xray = false
	ignore_opacity = true
	}
}

animations {
    enabled = true

    # Mindkét görbét definiáljuk, így nincs hiányzó hivatkozás
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = linear, 0.0, 0.0, 1.0, 1.0

    # Az ablakok a megszokott rugalmas görbét használják
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
    
    # A fénycsík pedig a tökéletesen egyenletes lineáris mozgást kapja
    animation = borderangle, 1, 80, linear, loop
}

