general {
    lock_cmd = quickshell -p ~/.config/quickshell/lock/shell.qml
    ignore_dbus_inhibit = false
}

# 5 perc (300 mp) tétlenség után zárolja a képernyőt.
# Nincs képernyő-kikapcsolás, suspend vagy hibernálás beállítva.

listener {
    timeout = 300
    on-timeout = quickshell -p ~/.config/quickshell/lock/shell.qml
}