general {
    lock_cmd = quickshell -p ~/.config/quickshell/lock/shell.qml
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = quickshell -p ~/.config/quickshell/lock/shell.qml
}