#!/usr/bin/env bash
set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CONFIG_HOME/hypr/hyprlab-settings"
STATE="$STATE_DIR/power.conf"
HYPRIDLE="$CONFIG_HOME/hypr/hypridle.conf"
mkdir -p "$STATE_DIR"

defaults() {
cat <<'EOD'
AUTO_LOCK=1
LOCK_MINUTES=5
DISPLAY_OFF=1
DISPLAY_OFF_AFTER_LOCK=5
SUSPEND=1
SUSPEND_AFTER_LOCK=20
EOD
}

[[ -f "$STATE" ]] || defaults > "$STATE"

save_key() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$STATE"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$STATE"
    else
        printf '%s=%s\n' "$key" "$value" >> "$STATE"
    fi
}

get_key() {
    local key="$1" fallback="$2"
    local value
    value="$(grep -E "^${key}=" "$STATE" | tail -n1 | cut -d= -f2- || true)"
    [[ -n "$value" ]] && printf '%s' "$value" || printf '%s' "$fallback"
}

bool_value() {
    case "$1" in
        1|true|on|yes) printf '1' ;;
        *) printf '0' ;;
    esac
}

positive_int() {
    local value="$1" fallback="$2"
    [[ "$value" =~ ^[0-9]+$ ]] && (( value >= 1 )) && printf '%s' "$value" || printf '%s' "$fallback"
}

render() {
    local auto_lock lock_minutes display_off display_after suspend suspend_after
    auto_lock="$(bool_value "$(get_key AUTO_LOCK 1)")"
    lock_minutes="$(positive_int "$(get_key LOCK_MINUTES 5)" 5)"
    display_off="$(bool_value "$(get_key DISPLAY_OFF 1)")"
    display_after="$(positive_int "$(get_key DISPLAY_OFF_AFTER_LOCK 5)" 5)"
    suspend="$(bool_value "$(get_key SUSPEND 1)")"
    suspend_after="$(positive_int "$(get_key SUSPEND_AFTER_LOCK 20)" 20)"

    local lock_seconds=$(( lock_minutes * 60 ))
    local display_seconds=$(( (lock_minutes + display_after) * 60 ))
    local suspend_seconds=$(( (lock_minutes + suspend_after) * 60 ))

    local tmp
    tmp="$(mktemp)"

    cat > "$tmp" <<EOD
general {
    # Generated by Hypr-Lab Settings. Edit power.conf through the UI instead.
    lock_cmd = quickshell -p ~/.config/quickshell/lock/shell.qml
    inhibit_sleep = 3
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}
EOD

    if [[ "$auto_lock" == "1" ]]; then
        cat >> "$tmp" <<EOD

# Automatic Hypr-Lab lock after ${lock_minutes} minute(s) idle.
listener {
    timeout = ${lock_seconds}
    on-timeout = loginctl lock-session
}
EOD

        if [[ "$display_off" == "1" ]]; then
            cat >> "$tmp" <<EOD

# Display standby ${display_after} minute(s) after the automatic lock point.
listener {
    timeout = ${display_seconds}
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
EOD
        fi

        if [[ "$suspend" == "1" ]]; then
            cat >> "$tmp" <<EOD

# Suspend ${suspend_after} minute(s) after the automatic lock point.
listener {
    timeout = ${suspend_seconds}
    on-timeout = systemctl suspend
}
EOD
        fi
    fi

    install -m 0644 "$tmp" "$HYPRIDLE"
    rm -f "$tmp"
}

restart_hypridle() {
    pkill -x hypridle 2>/dev/null || true
    sleep 0.15
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl dispatch exec hypridle >/dev/null 2>&1 || nohup hypridle >/dev/null 2>&1 &
    else
        nohup hypridle >/dev/null 2>&1 &
    fi
}

validate_key() {
    case "$1" in
        AUTO_LOCK|DISPLAY_OFF|SUSPEND|LOCK_MINUTES|DISPLAY_OFF_AFTER_LOCK|SUSPEND_AFTER_LOCK) ;;
        *) echo "Unknown power setting: $1" >&2; exit 2 ;;
    esac
}

case "${1:-}" in
    dump)
        cat "$STATE"
        ;;
    set)
        key="${2:?key}"
        value="${3:?value}"
        validate_key "$key"
        case "$key" in
            AUTO_LOCK|DISPLAY_OFF|SUSPEND) value="$(bool_value "$value")" ;;
            *) value="$(positive_int "$value" 1)" ;;
        esac
        save_key "$key" "$value"
        render
        restart_hypridle
        ;;
    apply)
        render
        restart_hypridle
        ;;
    render)
        render
        ;;
    reset)
        defaults > "$STATE"
        render
        restart_hypridle
        ;;
    *)
        echo "usage: $0 dump|set KEY VALUE|apply|render|reset" >&2
        exit 2
        ;;
esac
