WORKSPACE_COUNT=5
TOPBAR_WORKSPACES=1
TOPBAR_USB=1
TOPBAR_AUDIO=1
TOPBAR_NOTIFICATIONS=1
TOPBAR_CONTROL_CENTER=1
TOPBAR_LOCK_INDICATORS=1
TOPBAR_TRAY=1
TOPBAR_POWER=1
CENTER_VOLUME_FEEDBACK=1
CENTER_CAVA=1
CENTER_MEDIA_FEEDBACK=1
NOTIFICATION_SOUND=1
NOTIFICATION_SUMMARY=1
DND=0
DND_AUTO=1
DND_UNTIL=360
DND_FROM=1320
DND_MANUAL=0
